apiVersion: v1
kind: Secret
metadata:
  name: finguard-secrets
  namespace: finguard-ns
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  JWT_SECRET: ZmluZ3VhcmQtand0LXNlY3JldC1rZXktMjAyNg==
  OTEL_KEY: eW91ci1vdGVsLWtleS1oZXJl
