apiVersion: v1
kind: Service
metadata:
  name: finguard-app-service
  namespace: finguard-ns
spec:
  selector:
    app: finguard-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
    
