apiVersion: v1
kind: Secret
metadata:
  name: finguard-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # DB_USERNAME: postgres
  DB_USERNAME: "cG9zdGdyZXM="
  # DB_PASSWORD: change-me-in-production
  DB_PASSWORD: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  # JWT_SECRET: finguard-jwt-secret-key-2026
  JWT_SECRET: "ZmluZ3VhcmQtand0LXNlY3JldC1rZXktMjAyNg=="
  # OTEL_KEY: your-otel-key
  OTEL_KEY: "eW91ci1vdGVsLWtleQ=="
